services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - fromGroup: laravel-db
databases:
  - name: laravel-db
